n = int(input('Digite um número: '))
print('{}X 1 = {} || {}+1 = {}'.format(n, n*1, n, n+1))
print('{}X 2 = {} || {}+2 = {}'.format(n, n*2 ,n, n+2))
print('{}X 3 = {} || {}+3 = {}'.format(n, n*3, n, n+3))
print('{}X 4 = {} || {}+4 = {}'.format(n, n*4, n, n+4))
print('{}X 5 = {} || {}+5 = {}'.format(n, n*5, n, n+5))
print('{}X 6 = {} || {}+6 = {}'.format(n, n*6, n, n+6))
print('{}X 7 = {} || {}+7 = {}'.format(n, n*7, n, n+7))
print('{}X 8 = {} || {}+8 = {}'.format(n, n*8, n, n+8))
print('{}X 9 = {} || {}+9 = {}'.format(n, n*9, n, n+9))
print('{}X10 = {} || {}+10 = {}'.format(n, n*10, n, n+10))